apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    'backstage.io/kubernetes-id': dice-roller
spec:
  type: service
  lifecycle: production
  owner: user:ricardo.carvalho
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage
  description: Kubernetes object & Pipelines List for Backstage
  annotations:
    'dev.azure.com/project': Research
    'dev.azure.com/build-definition': Devscope-Backstage.backstage
    'backstage.io/kubernetes-id': backstage
  links:
    - url: https://backstage-bonfim.devscope.net/
      title: Backstage URL
    - url: https://github.com/Devscope-Backstage/backstage
      title: Backstage Repository
    - url: https://devscope365.sharepoint.com/sites/ithelpdeskGroup/_layouts/OneNote.aspx?id=%2Fsites%2FithelpdeskGroup%2FSiteAssets%2FITHelpDesk%20Group%20Notebook&wd=target%282023.one%7CC43EBA38-4268-4504-B646-677F20E9CA0C%2FBackstage%20Development%20%28Devscope%5C%29%7C03AAB081-F619-4781-BB29-631E7CFDD394%2F%29onenote:https://devscope365.sharepoint.com/sites/ithelpdeskGroup/SiteAssets/ITHelpDesk%20Group%20Notebook/2023.one#Backstage%20Development%20(Devscope)&section-id={C43EBA38-4268-4504-B646-677F20E9CA0C}&page-id={03AAB081-F619-4781-BB29-631E7CFDD394}&end
      title: Docs
spec:
  type: service
  lifecycle: production
  owner: backstage-maintainers
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Rooms
  description: Check Rooms availibility at devscope
  annotations:
    'dev.azure.com/project-repo': HostHelpdesk/MeetEasier
    'dev.azure.com/project': HostHelpdesk
    'dev.azure.com/build-definition': MeetEasier
    'backstage.io/kubernetes-id': meet-easier
  links:
    - url: https://rooms.aad-bonfim.devscope.net/
      title: Rooms URL
    - url: https://dev.azure.com/dvs/HostHelpdesk/_git/MeetEasier
      title: Rooms Repository
spec:
  type: service
  lifecycle: production
  owner: backstage-maintainers
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Kubernetes
  description: Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.
spec:
  owner: backstage-maintainers
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Bonfim
  description: Kubernetes Cluster do Bonfim
spec:
  owner: backstage-maintainers
  domain: Kubernetes
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Francos
  description: Kubernetes Cluster do Francos
spec:
  owner: backstage-maintainers
  domain: Kubernetes
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: SEQ00
  description: A virtual machine that supports logs from serilog
spec:
  type: VM
  owner: backstage-maintainers
  system: Kubernetes
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Serilog02
  description: Serilog provides diagnostic logging to files
  links:
    - url: https://serilog.aad-bonfim.devscope.net
      title: Serilog URL
spec:
  type: service
  lifecycle: production
  owner: backstage-maintainers
  system: Kubernetes
  dependsOn:
    - resource:SEQ00
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SerilogRemax
  description: Serilog provides diagnostic logging to files (Remax logs specific)
spec:
  type: service
  lifecycle: production
  owner: backstage-maintainers
  system: Kubernetes
  dependsOn:
    - component:Serilog02
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SerilogCore
  description: Serilog provides diagnostic logging to files (Core logs specific)
spec:
  type: service
  lifecycle: production
  owner: backstage-maintainers
  system: Kubernetes
  dependsOn:
    - component:Serilog02
