apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-templates
  description: A collection of Backstage templates
spec:
  type: url
  targets:
    - https://github.com/Devscope-Backstage/backstage-templates/blob/main/templates/blazor-template/template.yaml
    - https://github.com/Devscope-Backstage/backstage-templates/blob/main/templates/react-template/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/pull-request/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
    - https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml
    - https://github.com/Devscope-Backstage/backstage-templates/blob/main/templates/aspnet-template/template.yaml
