apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-v2
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: backstage-maintainers
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json